"""AI-powered article digest using Claude."""

import os
from datetime import datetime, timezone
from typing import Optional, List, Dict

ANTHROPIC_MODEL = "claude-sonnet-4-6"

GENRE_PROMPTS = {
    "cybersecurity": "Focus on: new CVEs, exploits, tools, and attack techniques. Flag anything critical or zero-day.",
    "ai_ml": "Focus on: new model releases, benchmark results, research breakthroughs, and practical applications.",
    "startups": "Focus on: funding rounds, product launches, acquisitions, and market trends relevant to solo founders.",
    "hardware": "Focus on: new chips, PCB projects, SDR discoveries, and maker community highlights.",
    "science": "Focus on: breakthroughs, experimental results, and papers with real-world implications.",
    "government": "Focus on: FOIA releases, policy changes, surveillance tech, and transparency wins.",
    "web_dev": "Focus on: new frameworks, performance improvements, security advisories, and browser changes.",
    "reverse_eng": "Focus on: new tools, techniques, malware analysis writeups, and CTF solutions.",
    "data_science": "Focus on: new datasets, visualization tools, statistical methods, and ML pipelines.",
    "niche": "Highlight the most unusual, obscure, or historically significant items.",
}

DEFAULT_PROMPT = "Summarize the most important and actionable items."


async def generate_digest(
    db_manager,
    genre: Optional[str] = None,
    limit: int = 50,
    mark_processed: bool = True,
) -> str:
    """
    Query unprocessed articles from DB, group by genre,
    summarize with Claude, return formatted markdown digest.
    """
    try:
        import anthropic
    except ImportError:
        return "[ERROR] anthropic library not installed. Run: pip install anthropic"

    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        return "[ERROR] ANTHROPIC_API_KEY environment variable not set."

    articles = await db_manager.get_unprocessed_articles(limit=limit, genre=genre)
    if not articles:
        return "No unprocessed articles found. Run `webreaper blogwatcher` first."

    # Group by genre
    by_genre: Dict[str, List[Dict]] = {}
    for a in articles:
        g = a.get("genre") or "general"
        by_genre.setdefault(g, []).append(a)

    client = anthropic.Anthropic(api_key=api_key)

    sections = []
    processed_ids = []

    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    sections.append(f"# WebReaper Daily Digest — {today}\n")

    for g, items in sorted(by_genre.items()):
        genre_label = g.replace("_", " ").title()
        focus = GENRE_PROMPTS.get(g, DEFAULT_PROMPT)

        # Build article list for prompt
        article_lines = []
        for i, a in enumerate(items, 1):
            text = a.get("summary") or a.get("content") or ""
            text = text[:800]  # Trim to keep prompt manageable
            article_lines.append(
                f"{i}. **{a['title']}**\n   Source: {a.get('source_feed', 'unknown')}\n   {text}"
            )

        articles_block = "\n\n".join(article_lines)

        prompt = f"""You are a technical intelligence analyst. Summarize these {len(items)} {genre_label} articles into a concise briefing.

{focus}

Format your response as:
- 3-5 bullet points of the most important items
- Each bullet: 1-2 sentences max
- Flag CRITICAL items with ⚠️
- No fluff, no hedging, direct and factual

Articles:
{articles_block}"""

        try:
            response = client.messages.create(
                model=ANTHROPIC_MODEL,
                max_tokens=600,
                messages=[{"role": "user", "content": prompt}]
            )
            summary = response.content[0].text.strip()
        except Exception as e:
            summary = f"[Summarization failed: {e}]"

        sections.append(f"## {genre_label} ({len(items)} articles)\n\n{summary}\n")
        processed_ids.extend([str(a["id"]) for a in items])

    # Mark as processed
    if mark_processed and processed_ids:
        await db_manager.mark_articles_processed(processed_ids)

    sections.append(f"\n---\n*{len(articles)} articles processed | Generated by WebReaper*")
    return "\n".join(sections)
